# Numpy

In [1]:
import numpy as np

In [2]:
# list, function

In [3]:
# scalar
x = np.array(10)
print(x)

10


In [4]:
# vector
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [5]:
# matrix
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [6]:
# function

In [7]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [8]:
x = np.arange(1, 5, 1) # (mwanzo, mwisho, tofauti)
print(x)

[1 2 3 4]


In [9]:
x = np.linspace(1, 5, 5) #(mwanzo, mwisho, idadi)
print(x)

[1. 2. 3. 4. 5.]


In [10]:
# matrix

In [11]:
x = np.zeros((4, 4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
x = np.ones((4, 4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
x = np.eye((4)) # identity matrix
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
x = np.random.random((3, 3))
x

array([[0.03315211, 0.5882816 , 0.28361899],
       [0.84258012, 0.58442371, 0.13364099],
       [0.73297044, 0.66482033, 0.82941251]])

shape, size, dimension

In [15]:
x = np.array([1, 2, 3])

In [16]:
x

array([1, 2, 3])

In [17]:
print(x.shape)

(3,)


In [18]:
print(x.size)

3


In [19]:
x.ndim

1

In [20]:
x = np.random.random((2, 3))
x

array([[0.51689276, 0.5075638 , 0.56693781],
       [0.40129722, 0.66878975, 0.59929599]])

In [21]:
x.shape

(2, 3)

In [22]:
x.size # idadi

6

In [23]:
x.ndim

2

#### Arithmetics (Mahesabu: +, -, *, /) 

In [24]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6]) #element-wise

In [25]:
x+y

array([5, 7, 9])

In [26]:
x-y

array([-3, -3, -3])

In [27]:
y-x

array([3, 3, 3])

In [28]:
x*y

array([ 4, 10, 18])

In [29]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
np.sum(x)

21

In [31]:
# Axis, 0, 1  0-rows, 1-columns

In [32]:
np.sum(x, axis=0) #rows

array([5, 7, 9])

In [33]:
# x.shape

In [34]:
np.sum(x, axis=1)

array([ 6, 15])

In [35]:
# dot product

In [36]:
# (2, 3) . (3, 2) = (2, 2)

In [37]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8], [9, 10], [11, 12]])

In [38]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [40]:
c = a.dot(b)

In [41]:
c

array([[ 58,  64],
       [139, 154]])

In [42]:
f"{a.shape} . {b.shape} = {c.shape}"

'(2, 3) . (3, 2) = (2, 2)'

In [43]:
# reshape

In [44]:
x = np.array([1, 2, 3, 4, 5, 6])
x

array([1, 2, 3, 4, 5, 6])

In [45]:
a = np.reshape(x, (2, 3))
a

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
# indexing and slicing

In [47]:
x = np.random.randint(1, 50, size=15)
x

array([ 3, 31, 20, 14,  5,  3, 30, 17, 36, 49, 18, 40, 25, 38,  5])

In [48]:
x[0] # namba ya kwanza

3

In [49]:
x[-1] # namba ya mwisho

5

In [50]:
x[1:5]

array([31, 20, 14,  5])

In [51]:
x = np.random.randint(1, 50, size=(2, 5))
x

array([[ 6,  9, 25, 25, 38],
       [19, 46, 16, 13,  7]])

In [52]:
x[:, 0] # columns

array([ 6, 19])

In [53]:
x[0, ] # rows

array([ 6,  9, 25, 25, 38])

In [54]:
x[x<24]

array([ 6,  9, 19, 16, 13,  7])

In [55]:
# cancatenate

In [56]:
a = np.ones((4, 4))
b = np.zeros((4, 4))

In [57]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [58]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
np.concatenate([a, b], axis=0)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
np.vstack([a, b])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
np.r_[a, b]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
np.concatenate([a, b], axis=1)

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

In [63]:
a.shape

(4, 4)

In [64]:
b.shape

(4, 4)

In [65]:
c = np.concatenate([a, b], axis=1)
c.shape

(4, 8)

In [66]:
# save and load

In [67]:
c

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

In [68]:
np.save('data.npy', c)

In [69]:
# load

In [70]:
c = np.load('data.npy')

In [71]:
c

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])